Create dockerfile and dockercompose
HealthHub-Management-System/Medical-Documentation-Service pull request #1
Opened 2024-04-15 17:41 UTC by KacperST

2024-04-20 16:46 UTC, michalszc requested changes

2024-04-20 16:46 UTC, michalszc commented on backend/docker-compose.yml
> +
missing newline

2024-04-20 16:46 UTC, michalszc commented on backend/requirements.txt
> +uvicorn==0.29.0
missing newline

2024-04-27 16:17 UTC, KacperST commented on backend/requirements.txt
> +uvicorn==0.29.0
Added

2024-05-03 11:57 UTC, Glonk223 approved these changes
Looks good

2024-05-03 13:04 UTC, michalszc approved these changes

2024-05-03 13:05 UTC, merged